### ISSUE TITLE
Building QtDeviser on Windows

### ISSUE THREAD

**Issue by bgoli** [sbmlteam/QtDeviser#1]
Here are some notes on building QtDeviser, where would you like them added, Wiki page, source?

Building QtDeviser
==================

This is a brief guide to building QtDeviser on Windows. It assumes the use of:

> Git for windows from <http://github.com>
> CMake 3.8.0 from <http://cmake.org>
> Qt 5.8.0 or newer from <https://www.qt.io>
> Visual Studio 2015 from <http://www.microsoft.com>

Getting the source
------------------

Clone the QtDeviser repository:

    git clone https://github.com/sbmlteam/QtDeviser.git

This should give you a directory called QtDeviser with the source code

Configure with CMAKE
--------------------

Run the cmake gui and point the source code path to the directory just created with git. Also set the binary build path to a different directory of your choosing, for example QtDeviser-build.

Press *Configure* select your build systems e.g., MSVC 2015 64bit. At this point anerror message may be displayed, close it and continue. Make sure the advanced box is checked and set the following value if it are not already configured (I installed Qt into D:/Qt please change this path to suit your installation).

>  **Qt5\_dir :** D:/Qt/Qt5.8.0/5.8/msvc2015\_64/lib/cmake/Qt5

*Configure* again set the following value:

>  **SELECT_QT :** Qt5
>  **CMAKE_INSTALL_PREFIX :** optional, set this if you want to use the INSTALL option 

*Configure* again and *Generate* the configuration files. If you are happy with the result press *Open Project* to continue

Building with Visual Studio 2015
--------------------------------

If everything has worked out you should be able to compile this without any modifications. At this point you need to select whether you will do a debug or release build, the following filenames are for a debug build. For a release build simply remove the trailing d. Right click on ALL\_BUILD and select *Build*. This should compile Deviser.

If successful the diviser will be in the binary build directory in a Release/Debug folder as **DeviserEdit.exe**. However, for this to work you probable need to copy the following files from your Qt distribution. In my case these were in \`d:QtQt5.8.05.8msvc2015\_64bin\`:

    Qt5CLucened.dll
    Qt5Cored.dll
    Qt5Guid.dll
    Qt5Helpd.dll
    Qt5Networkd.dll
    Qt5Sqld.dll
    Qt5Svgd.dll
    Qt5Widgetsd.dll
    Qt5Xmld.dll 

Execute DeviserEdit.exe and you should be good to go.

Brett G. Olivier, Amsterdam 2017

**Comment by mhucka** [comment]
@bgoli This is great! Very useful. 

As to location, I tend to prefer putting it as a file in the repo itself, mainly because I suspect (without empirical evidence) that people often don't think to look at GitHub wiki pages. @skeating and/or @fbergmann may have other opinions, but I would suggest creating a new top-level directory, **docs**, and putting it there as a markdown file with a self-describing file name.

**Comment by bgoli** [comment]
I created a docs subfolder and a branch with this document
